name: Auto Commit and Push

on:
  push:
    branches:
      - main  # Change this to your default branch

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'

    - name: Make changes
      run: |
        # Add the commands to make changes to your files here
        # For example, to update a file:
        # echo "New content" >> file.txt

    - name: Commit changes
      run: |
        git add .
        git commit -m "Automated commit by GitHub Actions"

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main  # Change this to your default branch
